[project]
name = "augmentarium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.0.3",
    "numpy==2.0.2",
    "pillow==10.4.0",
    "scikit-image==0.24.0",
]
